### ISSUE TITLE
Hide title when is empty.

### ISSUE THREAD

**Issue by mehdico** [TutorialsAndroid/KAlertDialog#1]
hi,
most of messages dont need a title. message like "do you want to move this?" not really need a title like "warning!". when we set title as empty "" , title textview can sets to gone for a better looking dialog.
thanks.

**Comment by TutorialsAndroid** [comment]
OK I will working on this library and will get a new version on next month

**Comment by TutorialsAndroid** [comment]
> 
> 
> hi,
> most of messages dont need a title. message like "do you want to move this?" not really need a title like "warning!". when we set title as empty "" , title textview can sets to gone for a better looking dialog.
> thanks.

we have fixed your issue now you can hide title text and content text of alert dialog for more info see the readme. see the new version of this library. **New version of this library doesn't support older android version as 85% of android devices support API 21+ and above**
