### ISSUE TITLE
Error after generate sign apk of my project

### ISSUE THREAD

**Issue by Jigs301** [TutorialsAndroid/KAlertDialog#11]
java.lang.RuntimeException: Unknown animation name: com.developer.kalert.Rotate3dAnimation error:com.developer.kalert.Rotate3dAnimation.<init>

**Comment by abhiTronix** [comment]
@Jigs301 Add this to your app proguard:

```txt
 -keep class com.developer.kalert.Rotate3dAnimation {
    public <init>(...);
 }
```

**Comment by Jigs301** [comment]
Thank you abhishek for you reply
