### ISSUE TITLE
Text in buttons appears cutted

### ISSUE THREAD

**Issue by erotundo** [TutorialsAndroid/KAlertDialog#16]
Hi!

Good component for use, i have a little problem because appears the text cutted.

Can i solved this?

**Comment by Proxcentaur** [comment]
i have the same problem

**Comment by erotundo** [comment]
@Proxcentaur 
After do some test i found the way to fix the height

put this in your theme file

`    <style name="dialog_blue_button" parent="android:Widget.Button">
        <item name="android:layout_width">wrap_content</item>
        <item name="android:layout_height">40dp</item>
        <item name="android:background">@drawable/button_background</item>
        <item name="android:textSize">14sp</item>
        <item name="android:paddingLeft">21dp</item>
        <item name="android:paddingRight">21dp</item>
        <item name="android:textColor">@color/button_text_color</item>
    </style>
`

And this to set the style to the button

`<item name="android:buttonStyle">@style/dialog_blue_button</item>
        <item name="buttonStyle">@style/dialog_blue_button</item>`
