### ISSUE TITLE
Dialog is too small 

### ISSUE THREAD

**Issue by JohnDominicJasmin** [TutorialsAndroid/KAlertDialog#17]
![272203569_630740791485447_1724037250865504910_n](https://user-images.githubusercontent.com/67941562/150638717-f3ace9af-87a9-4b20-b068-e7eedf4beb56.jpg)

**Comment by razvanrujoiu** [comment]
I have the same issue

**Comment by moisoni97** [comment]
@TutorialsAndroid please use this [scalable DP library](https://github.com/intuit/sdp) instead of the regular DP unit provided by Android to solve issues with fitting. That library will do a great, great job of scaling the view to any screen size.

**Comment by mariodantas** [comment]
Yes that still happens

**Comment by TutorialsAndroid** [comment]
Issue has been fixed in new version check it out. v15.0.19
