### ISSUE TITLE
cancelButtonColor not change the color

### ISSUE THREAD

**Issue by yuaneko95** [TutorialsAndroid/KAlertDialog#19]

**Comment by yuaneko95** [comment]
![image](https://user-images.githubusercontent.com/25382335/155250981-17cef00b-73f3-403b-96ca-eda3f06a6877.png)

**Comment by yuaneko95** [comment]
![image](https://user-images.githubusercontent.com/25382335/155251046-721aa48c-1d54-4215-90bb-4fc19ae3b2c7.png)

**Comment by yuaneko95** [comment]
![image](https://user-images.githubusercontent.com/25382335/155251101-eb1e8070-b3f3-4308-a497-3eaa4bc891cb.png)

this is my colors.xml

**Comment by TutorialsAndroid** [comment]
Issue has been fixed in latest version of library :-).  v16.0.19
