### ISSUE TITLE
New feature: set background color of confirm and cancel buttons

### ISSUE THREAD

**Issue by thomasvc** [TutorialsAndroid/KAlertDialog#2]
Hey,

Is it possible to add a method to set the background color of the confirm and cancel buttons?
This way the library is more usefull to include in project and it doesn't break the style of the application.

Kind regard,
Thomas

**Comment by TutorialsAndroid** [comment]
Yeah I will soon update this library. In next month.

**Comment by TutorialsAndroid** [comment]
I have updated the library now you can change the colors of buttons and customize the button with drawable too see the Readme

**Comment by thomasvc** [comment]
Thank you for the quick solution.
Works like a charm.

**Comment by TutorialsAndroid** [comment]
> 
> 
> Thank you for the quick solution.
> Works like a charm.

Note that the new version of this library doesn't support the older android version. As 85% of devices run on API 21+ and above.
