### ISSUE TITLE
Why does the constructor require a res-id?

### ISSUE THREAD

**Issue by oovvoo** [TutorialsAndroid/KAlertDialog#21]
I don't think this is necessary in most cases.

 KAlertDialog dialog = new KAlertDialog(context,KAlertDialog.WARNING_TYPE,0).

**Comment by TutorialsAndroid** [comment]
yeah i will surely do something for it...the ID is used to pass font-style to alert dialog..see the example below
`KAlertDialog dialog = new KAlertDialog(context,KAlertDialog.WARNING_TYPE, R.font.yourfont).`
