### ISSUE TITLE
Can't determine type for tag

### ISSUE THREAD

**Issue by it6masuyasby** [TutorialsAndroid/KAlertDialog#22]
after upgrading to version 19.0.91 why does this error appear ?
![image](https://user-images.githubusercontent.com/98723152/186062234-e48a832e-049d-4556-ab04-178d94fd2d08.png)

**Comment by TutorialsAndroid** [comment]
it's not 19.0.91 it is v19.0.19.. I will recommend to use latest version of library v20.0.0
