### ISSUE TITLE
NoClassDefFoundError: Failed resolution of: Landroid/webkit/TracingController;

### ISSUE THREAD

**Issue by murdak** [TutorialsAndroid/KAlertDialog#23]
KAlertDialog: v19.0.19
Device API 26

Compile SDk 32
Gradle Version 7.3.3
Gradle Plugin 7.2.1
Kotlin 1.6.10

Log:
I/zygote: Rejecting re-init on previously-failed class java.lang.Class<uJ>: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/webkit/TracingController;
I/zygote:     at java.lang.Class java.lang.Class.classForName(java.lang.String, boolean, java.lang.ClassLoader) (Class.java:-2)
I/zygote:     at java.lang.Class java.lang.Class.forName(java.lang.String, boolean, java.lang.ClassLoader) (Class.java:453)
I/zygote:     at java.lang.Class android.webkit.WebViewFactory.getWebViewProviderClass(java.lang.ClassLoader) (WebViewFactory.java:150)
I/zygote:     at java.lang.Class android.webkit.WebViewFactory.getProviderClass() (WebViewFactory.java:417)
I/zygote:     at android.webkit.WebViewFactoryProvider android.webkit.WebViewFactory.getProvider() (WebViewFactory.java:211)
I/zygote:     at android.webkit.WebViewFactoryProvider android.webkit.WebView.getFactory() (WebView.java:2467)
I/zygote:     at java.lang.String android.webkit.WebView.findAddress(java.lang.String) (WebView.java:1738)
I/zygote:     at void android.text.util.Linkify.gatherMapLinks(java.util.ArrayList, android.text.Spannable) (Linkify.java:550)
I/zygote:     at boolean android.text.util.Linkify.addLinks(android.text.Spannable, int) (Linkify.java:253)
I/zygote:     at void android.widget.TextView.setText(java.lang.CharSequence, android.widget.TextView$BufferType, boolean, int) (TextView.java:5328)
I/zygote:     at void android.widget.TextView.setText(java.lang.CharSequence, android.widget.TextView$BufferType) (TextView.java:5248)
I/zygote:     at void android.widget.TextView.setText(java.lang.CharSequence) (TextView.java:5205)
I/zygote:     at com.developer.kalert.KAlertDialog com.developer.kalert.KAlertDialog.setContentText(java.lang.String) (KAlertDialog.java:380)
I/zygote:     at void com.developer.kalert.KAlertDialog.onCreate(android.os.Bundle) (KAlertDialog.java:135)
I/zygote:     at void android.app.Dialog.dispatchOnCreate(android.os.Bundle) (Dialog.java:403)
I/zygote:     at void android.app.Dialog.show() (Dialog.java:302)

**Comment by TutorialsAndroid** [comment]
Without seeing your code can't excatly solve this issue. But for now i'm closing this issue. Let me know if your issue is fixed.
