### ISSUE TITLE
New Logo Proposal

### ISSUE THREAD

**Issue by chimzycash** [TutorialsAndroid/KAlertDialog#3]
Hi...
Just Came across your project and I really like it, I am a Logo/Icon Designer who really has the passion and loves to contribute to very nice open source projects, I want to create and Propose a new Logo/Icon for your project that will represent what your project is all about. 

Currently working on a few Idea Concept, I will share it here All For Free once I am done creating it, so you can give your feedback on any changes or adjustments you might want to suit your needs.

Your response would be really appreciated...

Regards!

**Comment by TutorialsAndroid** [comment]
> Hi...
> Just Came across your project and I really like it, I am a Logo/Icon Designer who really has the passion and loves to contribute to very nice open source projects, I want to create and Propose a new Logo/Icon for your project that will represent what your project is all about.
> 
> Currently working on a few Idea Concept, I will share it here All For Free once I am done creating it, so you can give your feedback on any changes or adjustments you might want to suit your needs.
> 
> Your response would be really appreciated...
> 
> Regards!

yeah. if you want to make a logo then can you make a logo for this project
