### ISSUE TITLE
problem with android manifests because constraint layout is upper than 1.3

### ISSUE THREAD

**Issue by RahimpourDeveloper** [TutorialsAndroid/KAlertDialog#6]
Hi, guys, your library is beautiful but also has a small problem
your preview library has also this problem
your library isn't matched with constraint layout 2 but it works fine with 1.3
please solve this problem thank you

**Comment by TutorialsAndroid** [comment]
> 
> 
> Hi, guys, your library is beautiful but also has a small problem
> your preview library has also this problem
> your library isn't matched with constraint layout 2 but it works fine with 1.3
> please solve this problem thank you

OK we will be soon solving this issue
