### ISSUE TITLE
How to disable confirm button ?

### ISSUE THREAD

**Issue by wigroms** [TutorialsAndroid/KAlertDialog#9]
Hi ,
I want to know how to disable confirm button  please make some method to Disable Confirm button Thank you.

**Comment by TutorialsAndroid** [comment]
> Hi ,
> I want to know how to disable confirm button please make some method to Disable Confirm button Thank you.

can you tell me for what reason you want to disable confirm button

**Comment by wigroms** [comment]
Business requirements need Disable confirm button or hide for Show only Message because dialog will auto disappear in 1 sec .

**Comment by TutorialsAndroid** [comment]
> Business requirements need Disable confirm button or hide for Show only Message because dialog will auto disappear in 1 sec .

Ok Bro....I will update this library.

**Comment by TutorialsAndroid** [comment]
> Business requirements need Disable confirm button or hide for Show only Message because dialog will auto disappear in 1 sec .

Hi I have updated the library as per your requirement just see the Readme File about how you can hide the confirm button....to hide confirm button 

To Hide Cancel And Confirm Button：

new KAlertDialog(this, KAlertDialog.CUSTOM_IMAGE_TYPE)
    .setTitleText("Sweet!")
    .setContentText("Here's a custom image.")
    .setCustomImage(R.drawable.custom_img)
    .setConfirmText("OK") //Do not call this if you don't want to show confirm button
    .setCancelText("CANCEL")//Do not call this if you don't want to show cancel button
    .show();
